### ISSUE TITLE
Discord API Error

### ISSUE THREAD

**Issue by good-repo** [Carcraftz/MirrorBot#5]
Recently stopped working, the bot does not start and gives this error
![unknown_2021 11 14-15 59](https://user-images.githubusercontent.com/84621585/141680032-4db6058c-b0e4-4f38-af1f-569f843380a7.png)

**Comment by adityasanehi** [comment]
Yep, the selfbot module seems depreceated, raises an API error while POSTing data or sending messages in this case. Here, I worked an alternate using simple discord.js to send the messages, while the listener user/bot is still on discord.js-selfbot-v11, feel free to use it for your work until the module is updated. https://github.com/adityasanehi/MirrorBotAlternate - [MirrorBot Alternate](https://github.com/adityasanehi/MirrorBotAlternate)
